const portfolio = {
  sectors: [
    {
      name: "Financial Sector",
      totalInvestment: 328450,
      percentage: 21,
      totalPresentValue: null,
      totalGainLoss: null,
      stocks: [
        {
          no: 1,
          name: "HDFC Bank",
          purchasePrice: 1490,
          qty: 50,
          investment: 74500,
          portfolioPercent: 5,
          nseBse: "HDFCBANK",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "Yes"
        },
        {
          no: 2,
          name: "Bajaj Finance",
          purchasePrice: 6466,
          qty: 15,
          investment: 96990,
          portfolioPercent: 6,
          nseBse: "BAJFINANCE",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        },
        {
          no: 3,
          name: "ICICI Bank",
          purchasePrice: 780,
          qty: 84,
          investment: 65520,
          portfolioPercent: 4,
          nseBse: "ICICIBANK",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "Yes"
        },
        {
          no: 4,
          name: "Bajaj Housing",
          purchasePrice: 130,
          qty: 504,
          investment: 65520,
          portfolioPercent: 4,
          nseBse: "BAJAJHFL",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "NA"
        },
        {
          no: 5,
          name: "Savani Financials",
          purchasePrice: 24,
          qty: 1080,
          investment: 25920,
          portfolioPercent: 2,
          nseBse: "511577",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "NA"
        }
      ]
    },
    {
      name: "Tech Sector",
      totalInvestment: 337820,
      percentage: 22,
      totalPresentValue: null,
      totalGainLoss: null,
      stocks: [
        {
          no: 1,
          name: "Affle India",
          purchasePrice: 1151,
          qty: 50,
          investment: 57550,
          portfolioPercent: 4,
          nseBse: "AFFLE",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "Yes"
        },
        {
          no: 2,
          name: "LTI Mindtree",
          purchasePrice: 4775,
          qty: 16,
          investment: 76400,
          portfolioPercent: 5,
          nseBse: "LTIM",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        },
        {
          no: 3,
          name: "KPIT Tech",
          purchasePrice: 672,
          qty: 61,
          investment: 40992,
          portfolioPercent: 3,
          nseBse: "KPITTECH",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        },
        {
          no: 4,
          name: "Tata Tech",
          purchasePrice: 1072,
          qty: 63,
          investment: 67536,
          portfolioPercent: 4,
          nseBse: "TATATECH",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        },
        {
          no: 5,
          name: "BLS E-Services",
          purchasePrice: 232,
          qty: 191,
          investment: 44312,
          portfolioPercent: 3,
          nseBse: "BLS",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "Yes"
        },
        {
          no: 6,
          name: "Tanla",
          purchasePrice: 1134,
          qty: 45,
          investment: 51030,
          portfolioPercent: 3,
          nseBse: "TANLA",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        }
      ]
    },
    {
      name: "Consumer",
      totalInvestment: 263565,
      percentage: 17,
      totalPresentValue: null,
      totalGainLoss: null,
      stocks: [
        {
          no: 1,
          name: "Dmart",
          purchasePrice: 3777,
          qty: 27,
          investment: 101979,
          portfolioPercent: 7,
          nseBse: "DMART",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        },
        {
          no: 2,
          name: "Tata Consumer",
          purchasePrice: 845,
          qty: 90,
          investment: 76050,
          portfolioPercent: 5,
          nseBse: "TATACONSUM",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        },
        {
          no: 3,
          name: "Pidilite",
          purchasePrice: 2376,
          qty: 36,
          investment: 85536,
          portfolioPercent: 6,
          nseBse: "PIDILITIND",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        }
      ]
    },
    {
      name: "Power",
      totalInvestment: 158860,
      percentage: 10,
      totalPresentValue: null,
      totalGainLoss: null,
      stocks: [
        {
          no: 1,
          name: "Tata Power",
          purchasePrice: 224,
          qty: 225,
          investment: 50400,
          portfolioPercent: 3,
          nseBse: "TATAPOWER",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        },
        {
          no: 2,
          name: "KPI Green",
          purchasePrice: 875,
          qty: 50,
          investment: 43750,
          portfolioPercent: 3,
          nseBse: "KPIGREEN",
          cmp: null,
          presentValue: null,
          gainLoss: null,
          gainLossPercent: null,
          peRatio: null,
          latestEarnings: null,
          marketCap: null,
          mustExit: "No"
        }
      ]
    }
  ]
};

module.exports = portfolio;
